name: counter_app
description: A simple Flutter app demonstrating fundamentals

dependencies:
  flutter:
    sdk: flutter

  # The following dependency is optional, uncomment if you use external packages
  # http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true